# Generated by Django 6.0.5 on 2026-07-02 00:45

import apps.solicitacoes.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parecer_operacional', models.TextField(blank=True, null=True)),
                ('aprovado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('protocolo', models.CharField(blank=True, max_length=20, unique=True)),
                ('nome_evento', models.CharField(max_length=200)),
                ('solicitante', models.CharField(max_length=200)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('data_evento', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('local', models.TextField()),
                ('publico_estimado', models.IntegerField()),
                ('observacoes', models.TextField(blank=True)),
                ('documento_sanitario', models.FileField(upload_to=apps.solicitacoes.models.upload_sanitario, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('documento_meio_ambiente', models.FileField(upload_to=apps.solicitacoes.models.upload_meio_ambiente, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('oficio_bombeiro', models.FileField(blank=True, null=True, upload_to=apps.solicitacoes.models.upload_bombeiro, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('oficio_comandante', models.FileField(blank=True, null=True, upload_to=apps.solicitacoes.models.upload_comandante, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('assinado_por', models.CharField(blank=True, max_length=200, null=True)),
                ('data_assinatura', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
