# Generated by Django 6.0.5 on 2026-07-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaAutorizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('posto', models.CharField(blank=True, max_length=20)),
                ('unidade', models.CharField(blank=True, max_length=80)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Matrícula Autorizada',
                'verbose_name_plural': 'Matrículas Autorizadas',
            },
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CORRECAO', 'Aguardando Correção'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20),
        ),
    ]
