# Generated by Django 6.0.5 on 2026-07-15 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0002_matriculaautorizada_alter_solicitacao_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='gerado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opos_geradas', to=settings.AUTH_USER_MODEL, verbose_name='OPO gerada por'),
        ),
    ]
