# Generated by Django 6.0.5 on 2026-07-24 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0003_solicitacao_gerado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesquisaSatisfacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('enviada', models.BooleanField(default=False)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('respondida', models.BooleanField(default=False)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('nota', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('solicitacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pesquisa', to='solicitacoes.solicitacao')),
            ],
        ),
    ]
