# Generated by Django 6.0.5 on 2026-07-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0004_pesquisasatisfacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='comentario_satisfacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='data_envio_pesquisa',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='data_resposta_pesquisa',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='nota_satisfacao',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='pesquisa_enviada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='pesquisa_respondida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='pesquisa_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='PesquisaSatisfacao',
        ),
    ]
